server:
  port: 5000
spring:
  application:
    name: spring-cloud-api-gateway
  main:
    web-application-type: reactive
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
eureka:
  client:
    serviceUrl:
     defaultZone: http://localhost:8761/eureka
    fetchRegistry: true
    registerWithEureka: true